openapi: "3.0.0"

info:
  title: "Single value extractor"
  description: "API that accepts a csv?, array?, something? and returns key:value pairs for any columns that only have a single value."
  version: "1.0"

paths:
  /extractsinglevalues:
    post:
      description: "Extract single values"

      requestBody:
        description: "Json with single field containing name of csv file or perhaps the array of values"
        required: true
        content:
          application/json: {}

      responses:
        '200':
          description: "Returns column names and their value for any column with only one value in all rows"
          content: 
           application/json: {}